# Generated by Django 5.2.6 on 2025-10-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userquizgoal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsession',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='testsession',
            name='status',
            field=models.CharField(default='in-progress', max_length=20),
        ),
    ]
