# Generated by Django 5.2.6 on 2025-11-24 18:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userquizprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon_url', models.URLField(blank=True, null=True)),
                ('icon_emoji', models.CharField(default='🏆', max_length=10)),
                ('criteria', models.JSONField(help_text='JSON defining the criteria for earning this badge')),
                ('category', models.CharField(choices=[('test', 'Test Achievement'), ('streak', 'Streak Achievement'), ('community', 'Community Achievement'), ('learning', 'Learning Achievement')], default='test', max_length=50)),
                ('points', models.IntegerField(default=10, help_text='Points awarded for earning this badge')),
            ],
        ),
        migrations.CreateModel(
            name='MockTestLeaderboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_id', models.CharField(max_length=255)),
                ('score', models.IntegerField()),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', 'timestamp'],
                'indexes': [models.Index(fields=['test_id', '-score'], name='api_mocktes_test_id_c5aa6e_idx'), models.Index(fields=['user', 'test_id'], name='api_mocktes_user_id_bbef3b_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_id', models.CharField(max_length=255)),
                ('question_text', models.TextField(blank=True, null=True)),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('user_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('correct_answer', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('time_spent', models.IntegerField(help_text='Time spent in seconds')),
                ('status', models.CharField(choices=[('correct', 'Correct'), ('incorrect', 'Incorrect'), ('skipped', 'Skipped'), ('marked', 'Marked for Review')], default='skipped', max_length=20)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='api.testsession')),
            ],
            options={
                'ordering': ['session', 'id'],
                'indexes': [models.Index(fields=['session', 'topic'], name='api_userans_session_5f88dd_idx'), models.Index(fields=['session', 'status'], name='api_userans_session_5baaa8_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
