# Generated by Django 5.2.6 on 2025-11-25 03:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_badge_mocktestleaderboard_useranswer_userbadge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField(help_text='HTML content from Froala editor')),
                ('word_count', models.IntegerField(default=0)),
                ('time_spent', models.IntegerField(default=0, help_text='Time spent in seconds')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='EssayReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_score', models.IntegerField(help_text='Overall score 0-100')),
                ('structure_score', models.IntegerField(help_text='Structure score 0-100')),
                ('coherence_score', models.IntegerField(help_text='Coherence score 0-100')),
                ('arguments_score', models.IntegerField(help_text='Arguments score 0-100')),
                ('language_score', models.IntegerField(help_text='Language score 0-100')),
                ('detailed_feedback', models.JSONField(help_text='Detailed feedback by section')),
                ('improvement_suggestions', models.JSONField(help_text='List of improvement suggestions')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('essay', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='api.essay')),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='EssayTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('domain', models.CharField(choices=[('science', 'Science & Technology'), ('politics', 'Politics & Governance'), ('philosophy', 'Philosophy & Ethics'), ('business', 'Business & Economics'), ('social', 'Social Issues'), ('environment', 'Environment & Sustainability'), ('arts', 'Arts & Culture'), ('current_affairs', 'Current Affairs')], max_length=50)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('context', models.TextField(help_text='Background information and context')),
                ('key_points', models.JSONField(help_text='Key points to address in the essay')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['domain', '-created_at'], name='api_essayto_domain_5788c3_idx'), models.Index(fields=['difficulty'], name='api_essayto_difficu_71ee73_idx')],
            },
        ),
        migrations.AddField(
            model_name='essay',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.essaytopic'),
        ),
        migrations.AddIndex(
            model_name='essay',
            index=models.Index(fields=['user', '-updated_at'], name='api_essay_user_id_220fa6_idx'),
        ),
        migrations.AddIndex(
            model_name='essay',
            index=models.Index(fields=['status'], name='api_essay_status_ddcd38_idx'),
        ),
    ]
