# Generated by Django 5.2.6 on 2025-12-08 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_essay_essayreview_essaytopic_essay_topic_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='XATEssayQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.CharField(max_length=50, unique=True)),
                ('passage_text', models.TextField(blank=True, null=True)),
                ('question_text', models.TextField()),
                ('solution_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='essay',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='essays', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='essay',
            name='xat_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.xatessayquestion'),
        ),
    ]
