# Generated by Django 5.2.6 on 2026-01-19 17:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_xatessayquestion_alter_essay_user_essay_xat_question'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_id', models.CharField(max_length=255)),
                ('question_data', models.JSONField()),
                ('subject', models.CharField(max_length=50)),
                ('next_review_date', models.DateField()),
                ('review_interval', models.IntegerField(default=2, help_text='Days until next review (2, 4, 6)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_review_date'],
            },
        ),
        migrations.CreateModel(
            name='UserDailySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('varc_questions', models.IntegerField(default=5)),
                ('dilr_questions', models.IntegerField(default=5)),
                ('qa_questions', models.IntegerField(default=5)),
                ('time_per_question', models.IntegerField(default=120, help_text='Time in seconds per question')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('subject', models.CharField(max_length=50)),
                ('questions', models.JSONField(help_text='List of question objects for this target')),
                ('is_completed', models.BooleanField(default=False)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date', 'subject')},
            },
        ),
    ]
