# Generated by Django 5.2.6 on 2026-01-20 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_revisionschedule_userdailysettings_dailytarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdailysettings',
            name='dilr_offset',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdailysettings',
            name='qa_offset',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdailysettings',
            name='varc_offset',
            field=models.IntegerField(default=0),
        ),
    ]
