# Generated by Django 5.2.6 on 2026-02-02 08:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_testsession_current_question_index_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PIBRelease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prid', models.CharField(help_text='Release ID from PIB (PRID query param)', max_length=50, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('ministry', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('quiz_data', models.JSONField(blank=True, help_text='Generated quiz questions', null=True)),
                ('original_url', models.URLField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
