# Generated by Django 5.2.6 on 2026-02-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_pibrelease_testsession_current_question_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='pibrelease',
            name='mains_questions',
            field=models.JSONField(blank=True, help_text='Generated Mains Q&A', null=True),
        ),
    ]
