# Generated by Django 5.2.6 on 2026-04-03 13:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_pibrelease_mains_questions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('article_id', models.CharField(help_text='Unique identifier (URL or hash)', max_length=255, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('source', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField(help_text='Full or partial content of the article')),
                ('summary', models.TextField(blank=True, null=True)),
                ('quiz_data', models.JSONField(blank=True, help_text='Generated quiz questions', null=True)),
                ('mains_questions', models.JSONField(blank=True, help_text='Generated Mains Q&A', null=True)),
                ('original_url', models.URLField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
