# Generated by Django 5.2.6 on 2026-06-20 09:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_testsession_current_question_index_upscmasterystate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionIRTParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_id', models.CharField(max_length=255, unique=True)),
                ('difficulty', models.FloatField(default=0.0, help_text='Parameter b: Difficulty of the question')),
                ('discrimination', models.FloatField(default=1.0, help_text='Parameter a: How well it discriminates ability')),
                ('guessing', models.FloatField(default=0.2, help_text='Parameter c: Probability of guessing correctly')),
                ('exposure_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='revisionschedule',
            name='ai_flashcard_content',
            field=models.JSONField(blank=True, help_text='AI generated flashcard with mnemonic, explanation, etc.', null=True),
        ),
        migrations.AddField(
            model_name='revisionschedule',
            name='exam_target',
            field=models.CharField(default='upsc', help_text='Target exam (e.g., upsc, cat)', max_length=50),
        ),
        migrations.CreateModel(
            name='TopicAbility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255)),
                ('theta', models.FloatField(default=0.0, help_text='Estimated user ability')),
                ('standard_error', models.FloatField(default=1.0, help_text='Standard error of the estimate')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irt_abilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
