# Generated by Django 5.2.6 on 2026-06-20 10:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_questionirtparameter_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        migrations.CreateModel(
            name='OptionalEvaluationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(default='mathematics', max_length=255)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='evaluations/')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('total_score', models.FloatField(blank=True, null=True)),
                ('max_score', models.FloatField(blank=True, null=True)),
                ('overall_feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('gemini_insights', models.JSONField(blank=True, help_text='Insights regarding trends, weak topics, and which questions to attempt more', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OptionalEvaluationQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_number', models.CharField(max_length=20)),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('marks_obtained', models.FloatField(blank=True, null=True)),
                ('max_marks', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluated_questions', to='api.optionalevaluationsession')),
            ],
        ),
    ]
