# Generated by Django 5.2.6 on 2026-06-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_testsession_current_question_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionalevaluationquestion',
            name='extracted_question_text',
            field=models.TextField(blank=True, help_text='The actual math problem text extracted from the PDF', null=True),
        ),
    ]
