# Generated by Django 5.2.6 on 2026-06-25 21:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_optionalevaluationquestion_extracted_question_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainsQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gs_paper', models.IntegerField(choices=[(1, 'GS-I'), (2, 'GS-II'), (3, 'GS-III'), (4, 'GS-IV')])),
                ('syllabus_topic', models.CharField(max_length=500)),
                ('question_text', models.TextField()),
                ('model_answer', models.TextField()),
                ('key_points', models.JSONField(default=list, help_text='Expected keywords, articles, or cases')),
            ],
        ),
        migrations.CreateModel(
            name='MainsEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_answer', models.TextField()),
                ('intro_score', models.IntegerField(help_text='Out of 10')),
                ('body_score', models.IntegerField(help_text='Out of 10')),
                ('conclusion_score', models.IntegerField(help_text='Out of 10')),
                ('structure_score', models.IntegerField(help_text='Out of 10')),
                ('factual_feedback', models.JSONField(default=list, help_text='List of missing articles/amendments/data')),
                ('structural_feedback', models.TextField()),
                ('overall_score', models.FloatField(default=0.0, help_text='Out of 10')),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mains_evaluations', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='api.mainsquestion')),
            ],
        ),
    ]
