# Frontend Dockerfile for Development
FROM node:20-alpine

# Set the working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the frontend code
COPY . /app

# Expose the port for the development server
EXPOSE 5000

# Start the development server
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
