[project]
name = "prepup"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "crawl4ai>=0.7.4",
    "django>=5.2.6",
    "django-cors-headers>=4.8.0",
    "django-restframework>=0.0.1",
    "djangorestframework>=3.16.1",
    "html5lib>=1.1",
    "playwright>=1.55.0",
    "psycopg2-binary>=2.9.10",
    "pytest>=8.4.2",
    "rapidfuzz>=3.14.1",
    "google-genai>=1.43.0",
    "drf-spectacular>=0.28.0",
    "pyyaml>=6.0.2",
    "asgiref>=3.8.1",
    "sqlparse>=0.5.0",
    "inflection>=0.5.1",
    "uritemplate>=4.1.1",
    "pydantic>=2.7.1",
    "telethon>=1.41.2",
    "telethon>=1.41.2",
    "langchain-core>=1.0.1",
    "langgraph>=1.0.1",
    "langchain-google-genai>=3.0.0",
    "uvicorn>=0.38.0",
    "langgraph-checkpoint-sqlite>=3.0.0",
    "pydantic-settings>=2.11.0",
    "langchain>=1.0.2",
    "deepagents>=0.2.4",
    "langchain-google-community>=3.0.0",
    "pyjwt>=2.10.1",
    "adrf>=0.1.12",
    "celery>=5.5.3",
    "redis>=7.1.0",
    "requests>=2.31.0",
    "pypdf>=6.4.0",
    "pypdf2>=3.0.1",
    "img2pdf>=0.6.3",
    "notebooklm-py[browser]>=0.3.1",
]
