# Generated by Django 5.2.6 on 2025-10-16 07:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuizGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('quiz_id', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('total_questions', models.PositiveIntegerField(default=10)),
                ('completed_questions', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_quiz_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date', 'quiz_id')},
            },
        ),
    ]
