# Generated by Django 5.2.6 on 2025-10-17 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_dailyquizgoal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyQuizGoal',
        ),
    ]
