"""
State definitions and Pydantic models for SOPForge.
"""

from typing import TypedDict, Optional, Annotated
from langchain_core.messages import BaseMessage, add_messages


class GraphState(TypedDict):
    """
    Shared state passed between all graph nodes.
    
    This is the single source of truth for all agent communications,
    research findings, and drafts throughout the SOP generation process.
    """
    
    # User-provided inputs
    user_prompt: str
    """The user's primary request, e.g., 'MS in CS at Stanford focusing on AI'"""
    
    user_profile: str
    """User's resume, experiences, and background as plain text"""
    
    # Agent-generated content
    research_plan: list[str]
    """List of search queries generated by the Planner"""
    
    research_findings: str
    """Synthesized research summary from web searches"""
    
    draft: str
    """Current version of the SOP being generated"""
    
    review_notes: str
    """Reviewer's critique: 'PERFECT' or bulleted revision list"""
    
    # Control flow
    iteration_count: int
    """Counter to prevent infinite review/edit loops"""
    
    human_feedback: Optional[str]
    """User input at the HITL checkpoint: 'APPROVE' or new instructions"""
    
    # LangChain message history for tracing
    messages: Annotated[list[BaseMessage], add_messages]
    """Message history for observability and debugging"""


class SOPForgeConfig:
    """Configuration constants for SOPForge."""
    
    # Model settings
    PLANNER_MODEL = "gemini-2.5-flash"
    WRITER_MODEL = "gemini-1.5-pro"
    REVIEWER_MODEL = "gemini-2.5-flash"
    EDITOR_MODEL = "gemini-1.5-pro"
    
    # Graph behavior
    MAX_ITERATIONS = 3
    """Maximum review/edit cycles before forcing user approval"""
    
    RESEARCH_QUERIES_LIMIT = 5
    """Maximum number of search queries from planner"""
    
    # Search settings
    SEARCH_RESULTS_PER_QUERY = 3
    """Results per Google Search query"""
    
    # Token limits (conservative)
    MAX_DRAFT_TOKENS = 2500
    """Approximate token budget for SOP draft"""


class PlannedResearch(TypedDict):
    """Output structure from Planner node."""
    queries: list[str]
    reasoning: str


class ReviewResult(TypedDict):
    """Output structure from Reviewer node."""
    status: str  # "PERFECT" or "REVISE"
    feedback: str  # Empty or bulleted list

def create_initial_state(user_prompt: str, user_profile: str) -> GraphState:
    """Factory function to create initial graph state."""
    return GraphState(
        user_prompt=user_prompt,
        user_profile=user_profile,
        research_plan=[],
        research_findings="",
        draft="",
        review_notes="",
        iteration_count=0,
        human_feedback=None,
        messages=[]
    )
