const MONTHS = ['','Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
const DAYS = ['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];
// ─── SCHEDULE DATA ────────────────────────────────────────────────────────────
// Key: GS labels, Math topics per day, Language progression, Evening sessions

// Evening sessions rotate: CA = Current Affairs (Hindu/IE), Rev = Revision, Test = self-test
// Language progression:
// May-Jun (months 1-2): Eng newspaper 30min + basic Odia reading
// Jul-Sep (months 3-5): Précis practice 2x/week + letter writing 1x/week
// Oct-Dec (months 6-8): Essay outline 1x/week + translation practice + Odia composition
// Jan-Apr (months 9-12): Full paper practice – 2 full language papers/month

function langNote(monthNum) {
  if (monthNum <= 2) return 'Language (30 min):\nEnglish: The Hindu reading\nOdia: Basic reading practice';
  if (monthNum <= 5) return 'Language (45 min):\nEnglish: Précis / letter writing\nOdia: Paragraph writing';
  if (monthNum <= 8) return 'Language (60 min):\nEnglish: Essay outline / translation\nOdia: Composition practice';
  return 'Language (90 min):\nEnglish: Full paper practice\nOdia: Full paper practice';
}

// Math 22-week plan mapped to day numbers starting from Day 1 = May 4, 2026
const mathByDay = {
  // WEEK 1-2: Linear Algebra
  1: 'LINEAR ALGEBRA (W1–2)\nAlgebra of Matrices\nRow & col reduction; congruences & similarity',
  2: 'LINEAR ALGEBRA\nSymmetric, skew-sym, Hermitian\nSkew-Herm, Orthogonal, Unitary matrices',
  3: 'LINEAR ALGEBRA\nRank of matrix; Echelon form\nNormal form',
  4: 'LINEAR ALGEBRA\nInverse of matrix\nSystem of linear equations (methods)',
  5: 'LINEAR ALGEBRA\nEigenvalues, eigenvectors\nCharacteristic polynomial',
  6: 'LINEAR ALGEBRA (Weekend)\nCayley-Hamilton Theorem\nDiagonalizable matrices',
  7: 'LINEAR ALGEBRA (Weekend)\nQuadratic Form; Index & Signature\nPractice: Krishna Series Matrices',
  8: 'LINEAR ALGEBRA\nPractice: Eigen Values problems\nLinear Equations; Orthogonal (Krishna)',
  9: 'LINEAR ALGEBRA\nPractice: Quadratic Forms (Krishna)\nSimilarity & Diagonalization',
  10: 'LINEAR ALGEBRA\nVector spaces – definition & problems\nSubspaces, Bases, Dimension',
  11: 'LINEAR ALGEBRA\nLinear Transformations – rank & nullity\nLT Isomorphism; Singular; Invertibles',
  12: 'LINEAR ALGEBRA\nMatrix of a Linear Transformation\nChange of Bases',
  13: 'LINEAR ALGEBRA (Weekend)\nReview: Vector spaces & LT\nMixed problems practice',
  14: 'LINEAR ALGEBRA (Weekend)\n★ SELF-TEST: Full LA paper (2 hrs)\nReview answers & gaps',
  // WEEK 3: Numerical Analysis
  15: 'NUMERICAL ANALYSIS (W3)\nBisection method; Newton-Raphson\nRegula Falsi method',
  16: 'NUMERICAL ANALYSIS\nNewton Forward & Backward interpolation\nLagrange interpolation + error analysis',
  17: 'NUMERICAL ANALYSIS\nTrapezoid rule; Simpson\'s rule\nError analysis & derivation',
  18: 'NUMERICAL ANALYSIS\nODE: Euler method\nRunge-Kutta (RK4) method',
  19: 'NUMERICAL ANALYSIS\nGauss Jordan; Gauss-Seidel methods\nError analysis in linear systems',
  20: 'NUMERICAL ANALYSIS (Weekend)\nBoolean algebra practice problems\nAlgorithms & Flowcharts',
  21: 'NUMERICAL ANALYSIS (Weekend)\n★ NA Review + Spot Test\nStart Vector Analysis overview',
  // WEEK 4: Vector Analysis
  22: 'VECTOR ANALYSIS (W4)\nGradient, Divergence, Curl\n(Cartesian, Cylindrical, Spherical)',
  23: 'VECTOR ANALYSIS\nVector identity problems\nApplications in coordinate systems',
  24: 'VECTOR ANALYSIS\nLine integrals; Green\'s Theorem\nProblems & verification',
  25: 'VECTOR ANALYSIS\nGauss Divergence Theorem\nProblems & applications',
  26: 'VECTOR ANALYSIS\nStokes\' Theorem – problems\nSurface integrals',
  27: 'VECTOR ANALYSIS (Weekend)\nCurves in space – tangent, normal eqns\nCurvature & Torsion',
  28: 'VECTOR ANALYSIS (Weekend)\nSerret-Frenet Formula + problems\n★ VA Review & Spot Test',
  // WEEK 5-6: ODE
  29: 'ODE (W5–6)\nFormation of ODEs\nIntegrating factors; methods',
  30: 'ODE\nEquations of 1st Order (all types)\nSolvable for p, x, y',
  31: 'ODE\nTrajectory (orthogonal & oblique)\nClairaut\'s equation',
  32: 'ODE\nSingular solutions\nLinear DEs with constant coefficients',
  33: 'ODE\nCauchy-Euler equation\nMethod of Variation of Parameters',
  34: 'ODE (Weekend)\nSimultaneous DEs\nLinear Equations of Order 2',
  35: 'ODE (Weekend)\nNormal form; Variable transformation\nReduction of order methods',
  36: 'ODE\nLaplace Transform – definition, properties\nLT of standard functions',
  37: 'ODE\nInverse Laplace Transform\nPartial fraction method; convolution',
  38: 'ODE\nApplication of Laplace to ODEs\nSolving IVPs using Laplace',
  39: 'ODE\nODE comprehensive problems\nMixed types practice',
  40: 'ODE (Weekend)\nODE higher order problems\nPractice set – Krishna Series',
  41: 'ODE (Weekend)\n★ SELF-TEST: ODE Full Paper\nReview + gaps identification',
  42: 'ODE\nODE buffer – weak topics\nAny remaining ODE concepts',
  // WEEK 7-8: PDE
  43: 'PDE (W7–8)\nFormation of PDEs; examples\nOrder, degree & classification',
  44: 'PDE\nLinear PDE – 1st Order\nLagrange\'s method; standard forms',
  45: 'PDE\nNon-linear PDE – Charpit\'s method\nStandard form solutions (Types 1–4)',
  46: 'PDE\nJacobi method\nCauchy strip problem',
  47: 'PDE\nHomogeneous linear PDE (const coeff)\nComplementary function methods',
  48: 'PDE (Weekend)\nNon-homogeneous PDE\nEuler-Cauchy methods',
  49: 'PDE (Weekend)\nCanonical forms (Elliptic/Parabolic/Hyperbolic)\nClassification & transformation',
  50: 'PDE\nBoundary Value Problems\nHeat Equation (separation of variables)',
  51: "PDE\nWave Equation – d'Alembert's solution\nNormal modes",
  52: 'PDE\nLaplace Equation\nSolution in rectangular domain',
  53: 'PDE\nPolar coordinate systems\nSolution in circular domain',
  54: 'PDE (Weekend)\nCylindrical & Spherical systems\nBessel & Legendre introduction',
  55: 'PDE (Weekend)\n★ PDE Self-Test (full paper)\nReview + weak topics',
  56: 'PDE\nPDE comprehensive problems\nPYQ type problems',
  // WEEK 9-11: Calculus & Real Analysis
  57: 'CALCULUS & REAL ANALYSIS (W9–11)\nLimits & Continuity – definitions\nEpsilon-delta proofs',
  58: 'CALCULUS\nDifferentiability; examples & counter-examples\nMVT family of theorems',
  59: 'CALCULUS\nMean Value Theorems (Rolle\'s, Lagrange, Cauchy)\nApplications',
  60: 'CALCULUS\nIndeterminate forms – L\'Hopital\'s rule\nTaylor series expansions',
  61: 'CALCULUS\nMaxima & Minima – Lagrange multipliers\n2D constrained optimization',
  62: 'CALCULUS (Weekend)\nJacobians; transformations\nMaxima/minima problems',
  63: 'CALCULUS (Weekend)\nAsymptotes (horizontal, vertical, oblique)\nPartial derivatives',
  64: 'REAL ANALYSIS\nRiemann integral – definitions\nDarboux sums; properties',
  65: 'REAL ANALYSIS\nTheorems on Riemann integral\nFundamental theorem of calculus',
  66: 'REAL ANALYSIS\nImproper integrals – Type I & II\nTests for convergence',
  67: 'REAL ANALYSIS\nImproper integrals – problems\nGamma integral',
  68: 'REAL ANALYSIS (Weekend)\nSequences – basic definitions\nMonotone convergence; Bolzano-Weierstrass',
  69: 'REAL ANALYSIS (Weekend)\nSeries – tests for convergence\nComparison, ratio, root tests',
  70: 'REAL ANALYSIS\nSeries – advanced tests\nAlternating series; absolute convergence',
  71: 'REAL ANALYSIS\nUniform convergence – definitions\nWeierstrass M-test',
  72: 'REAL ANALYSIS\nUniform convergence: continuity\nDifferentiability & integrability properties',
  73: 'CALCULUS\nMultiple integrals – change of order\nDouble integrals; Fubini\'s theorem',
  74: 'CALCULUS (Weekend)\nDouble & Triple integrals; areas\nChange of variables',
  75: 'CALCULUS (Weekend)\nSurface areas; Volumes\nLine & surface integrals (review)',
  76: 'CALCULUS\nBeta & Gamma functions\nProperties; applications',
  77: 'CALCULUS\nIntegration under differentiation sign\nLeibniz rule; applications',
  78: 'CALCULUS\nCalculus & RA comprehensive problems\nPYQ type questions',
  79: 'CALCULUS (Weekend)\n★ SELF-TEST: Calculus & RA Full Paper\nReview + gap analysis',
  // WEEK 12: Complex Analysis
  80: 'COMPLEX ANALYSIS (W12)\nAnalytic functions – C-R equations\nHarmonic functions',
  81: 'COMPLEX ANALYSIS\nComplex integration – definition\nCauchy\'s theorem; Cauchy\'s integral formula',
  82: 'COMPLEX ANALYSIS\nComplex integration – problems\nCauchy\'s integral formula (higher order)',
  83: 'COMPLEX ANALYSIS\nTaylor series; Laurent series\nRadius of convergence',
  84: 'COMPLEX ANALYSIS\nSingularities (removable, poles, essential)\nMeromorphic functions; Power series',
  85: 'COMPLEX ANALYSIS (Weekend)\nResidue theorem\nPoles & residues computation',
  86: 'COMPLEX ANALYSIS (Weekend)\nContour integration problems\n★ Complex Analysis Spot Test',
  // WEEK 13-14: Analytic Geometry
  87: 'ANALYTIC GEOMETRY (W13–14)\nDirection cosines & ratios\nProjections; angle between lines',
  88: 'ANALYTIC GEOMETRY\nPlanes – general & intercept form\nAngle; distance; family of planes',
  89: 'ANALYTIC GEOMETRY\nStraight lines – symmetric form\nPassing through intersection of planes',
  90: 'ANALYTIC GEOMETRY\nStraight lines problems\nAngle between line & plane; intersection',
  91: 'ANALYTIC GEOMETRY\nShortest distance between skew lines\nTetrahedron problems',
  92: 'ANALYTIC GEOMETRY (Weekend)\nSkew lines; conditions for intersection\nSpheres – general equation',
  93: 'ANALYTIC GEOMETRY (Weekend)\nCylinder – equation & problems\nCones – vertex & generators',
  94: 'ANALYTIC GEOMETRY\nCones – problems\nCentral Conicoid Part 1 (ellipsoid)',
  95: 'ANALYTIC GEOMETRY\nCentral Conicoid Part 2 (hyperboloid)\nTangent plane & normal',
  96: 'ANALYTIC GEOMETRY\nCentral Conicoid Part 3\nPolar plane; conjugate diameters',
  97: 'ANALYTIC GEOMETRY\nParaboloid – elliptic & hyperbolic\nProperties & problems',
  98: 'ANALYTIC GEOMETRY (Weekend)\nGenerating lines Part 1\nRuled surfaces',
  99: 'ANALYTIC GEOMETRY (Weekend)\nGenerating lines Part 2\n★ AG Self-Test + Review',
  100: 'ANALYTIC GEOMETRY\nAG comprehensive problems\nPYQ type questions',
  // WEEK 15: LPP
  101: 'LINEAR PROGRAMMING (W15)\nDefinitions; convex sets; feasible region\nFormulation of LPP problems',
  102: 'LINEAR PROGRAMMING\nGraphical method – 2 variables\nCorner point theorem',
  103: 'LINEAR PROGRAMMING\nSimplex method Part 1\nBig-M method',
  104: 'LINEAR PROGRAMMING\nSimplex method – Duality\nDual simplex; complementary slackness',
  105: 'LINEAR PROGRAMMING\nAssignment problems\nHungarian method',
  106: 'LINEAR PROGRAMMING (Weekend)\nAssignment problems – advanced\nMaximization assignment',
  107: 'LINEAR PROGRAMMING (Weekend)\nTransportation problems\nNorth-west corner; Vogel\'s method',
  108: 'LINEAR PROGRAMMING\nTransportation – MODI method\nDegeneracy; unbalanced problems\n★ LPP Spot Test',
  // WEEK 16: Mechanics
  109: 'MECHANICS (W16)\nMoment of inertia\nParallel & perpendicular axes theorems',
  110: 'MECHANICS\nLagrangian mechanics Part 1\nGeneralized coordinates; Lagrange\'s equations',
  111: 'MECHANICS\nLagrangian mechanics Part 2\nProblems on Lagrange\'s equations',
  112: 'MECHANICS\nHamiltonian mechanics Part 1\nHamiltonian function; Hamilton\'s equations',
  113: 'MECHANICS\nHamiltonian mechanics Part 2\nCanonical transformations; problems',
  114: 'MECHANICS (Weekend)\nD\'Alembert\'s principle\nVirtual work; constraints',
  115: 'MECHANICS (Weekend)\nMotion of rigid bodies in 2D Part 1\nRolling motion; impulsive forces',
  116: 'MECHANICS\nMotion in 2D Part 2 (selected problems)\n★ Mechanics Spot Test + Review',
  // WEEK 17-18: Fluid Dynamics
  117: 'FLUID DYNAMICS (W17–18)\nKinematics; Lagrange & Euler description\nVelocity; acceleration; continuity eqn',
  118: 'FLUID DYNAMICS\nBoundary conditions\nStreamlines; stream function',
  119: 'FLUID DYNAMICS\nPath lines; streaklines\nVelocity potential; irrotational flow',
  120: 'FLUID DYNAMICS\nEuler\'s equations of motion\nDerivation & applications',
  121: 'FLUID DYNAMICS\nImpulsive motion\nEnergy equation; Bernoulli\'s equation (derivation)',
  122: 'FLUID DYNAMICS (Weekend)\nBernoulli\'s equation problems\nApplications (pitot tube, venturi)',
  123: 'FLUID DYNAMICS (Weekend)\nStream functions; source & sink\nDoublet; uniform flow',
  124: 'FLUID DYNAMICS\nImages in 2D flow\nCircle images; method of images',
  125: 'FLUID DYNAMICS\nIrrotational motion – complex potential\nComplex velocity',
  126: 'FLUID DYNAMICS\nNavier-Stokes equations\nDerivation; physical interpretation',
  127: 'FLUID DYNAMICS (Weekend)\nLaminar flow – Poiseuille\'s flow\nCouette flow',
  128: 'FLUID DYNAMICS (Weekend)\nFluid dynamics comprehensive problems\n★ FD Self-Test',
  // WEEK 19-20: Abstract Algebra
  129: 'ABSTRACT ALGEBRA (W19–20)\nBinary operations; algebraic structures\nGroups – definition & examples',
  130: 'ABSTRACT ALGEBRA\nSubgroups – definition & theorems\nProblems on subgroups',
  131: 'ABSTRACT ALGEBRA\nCyclic groups & subgroups\nOrder of element; generators',
  132: 'ABSTRACT ALGEBRA\nCosets – Lagrange\'s theorem\nApplications',
  133: 'ABSTRACT ALGEBRA\nNormal subgroups – definition\nQuotient groups',
  134: 'ABSTRACT ALGEBRA (Weekend)\nGroup homomorphisms\nFirst, Second, Third isomorphism theorems',
  135: 'ABSTRACT ALGEBRA (Weekend)\nPermutation groups – Sn, An\nCycles; transpositions; even/odd',
  136: 'ABSTRACT ALGEBRA\nSylow theorems (1st, 2nd, 3rd)\nApplications to classify groups',
  137: 'ABSTRACT ALGEBRA\nRings & subrings – definition & examples\nIntegral domains; fields',
  138: 'ABSTRACT ALGEBRA\nIdeals – principal, maximal, prime\nQuotient rings',
  139: 'ABSTRACT ALGEBRA\nRing homomorphism – isomorphism theorems\nEmbedding; characteristic',
  140: 'ABSTRACT ALGEBRA (Weekend)\nMaximal & prime ideals\nField of fractions',
  141: 'ABSTRACT ALGEBRA (Weekend)\nEuclidean domains (ED)\nPrincipal ideal domains (PID)',
  142: 'ABSTRACT ALGEBRA\nUnique factorization domains (UFD)\nEisenstein\'s criterion; irreducibility',
  143: 'ABSTRACT ALGEBRA\nAbstract Algebra PYQ practice\n★ Algebra Self-Test',
  // WEEK 21: Dynamics
  144: 'DYNAMICS (W21)\nBasic concepts; rectilinear motion\nVelocity; acceleration; Newton\'s laws',
  145: 'DYNAMICS\nSimple Harmonic Motion (SHM)\nPeriod; amplitude; energy in SHM',
  146: 'DYNAMICS\nProjectile motion\nRange; maximum height; time of flight',
  147: 'DYNAMICS\nPlane kinematics\nCircular motion; relative motion',
  148: 'DYNAMICS\nCentral orbits; conic sections\nAreal velocity; apse',
  149: 'DYNAMICS (Weekend)\nPlanetary motion – Kepler\'s laws\nTime of flight; anomalies',
  150: 'DYNAMICS (Weekend)\nConstrained motion – bead on wire/curve\nMotion in circle (inside/outside)\n★ Dynamics Spot Test',
  // WEEK 22: Statics
  151: 'STATICS (W22)\nPrinciple of Virtual Work\nVirtual displacements; conservative forces',
  152: 'STATICS\nVirtual work – problems\nForce systems; equilibrium conditions',
  153: 'STATICS\nStability & instability of equilibrium\nPotential energy test',
  154: 'STATICS\nStability problems\nEquilibrium of bodies (rigid)',
  155: 'STATICS\nCatenary – common catenary\nEquation; tension; shape',
  156: 'STATICS (Weekend)\nCatenary problems\nHeavy chain; suspension bridges',
  157: 'STATICS (Weekend)\n★ STATICS SELF-TEST\n22-WEEK PLAN COMPLETE!\nFull review & gap list',
};

// Revision cycles (Oct 2026 onwards)
function revMath(topic, dayStr) {
  return `REVISION CYCLE\n${topic}\nPYQ practice + Answer writing (${dayStr})`;
}

// GS schedule from UPSC Essential timetable
const gsByDate = {
  // PHASE 1: GS Foundation (pre-recorded, watch as per schedule)
  '2026-05-04': 'GS FOUNDATION (Pre-recorded)\nFoundation of Geography 01\nGeography NCERTs',
  '2026-05-05': 'GS FOUNDATION\nFoundation of Geography 02\nGeography NCERTs',
  '2026-05-06': 'GS SELF-STUDY\nGeography NCERT revision\n+ notes making',
  '2026-05-07': 'GS FOUNDATION\nFoundation of Geography 03\nGeography NCERTs',
  '2026-05-08': 'GS FOUNDATION\nFoundation of Geography 04\nGeography NCERTs',
  '2026-05-09': 'GS SELF-STUDY (Weekend)\nGeography: Week 1 revision\n+ mind maps',
  '2026-05-10': 'GS SELF-STUDY (Sunday)\nGeography NCERT notes\n+ questions practice',
  '2026-05-11': 'GS FOUNDATION\nFoundation of Geography 05\nGeography NCERTs',
  '2026-05-12': 'GS FOUNDATION\nFoundation of Geography 06\nGeography NCERTs',
  '2026-05-13': 'GS SELF-STUDY\nGeography full NCERT review\n+ flowcharts',
  '2026-05-14': 'GS FOUNDATION\nFoundation of Indian Polity 01\nPolity NCERTs',
  '2026-05-15': 'GS FOUNDATION\nFoundation of Indian Polity 02\nPolity NCERTs',
  '2026-05-16': 'GS SELF-STUDY (Weekend)\nPolity NCERTs revision\n+ notes',
  '2026-05-17': 'GS SELF-STUDY (Sunday)\nGeography + Polity revision\n+ MCQ practice',
  '2026-05-18': 'GS FOUNDATION\nFoundation of Indian Polity 03\nPolity NCERTs',
  '2026-05-19': 'GS FOUNDATION\nFoundation of Indian Polity 04\nPolity NCERTs',
  '2026-05-20': 'GS FOUNDATION\nFoundation of Indian Polity 05\nPolity NCERTs',
  '2026-05-21': 'GS FOUNDATION\nFoundation of Indian Polity 06\nPolity NCERTs',
  '2026-05-22': 'GS FOUNDATION\nFoundation of Indian Polity 07\nPolity NCERTs',
  '2026-05-23': 'GS FOUNDATION\nFoundation of Indian Polity 08\nPolity NCERTs',
  '2026-05-24': 'GS SELF-STUDY (Sunday)\nPolity full revision\n+ previous year MCQs',
  '2026-05-25': 'GS FOUNDATION\nFoundation of Ancient & Medieval History 01\nNCERT',
  '2026-05-26': 'GS FOUNDATION\nFoundation of Ancient & Medieval History 02\nNCERT',
  '2026-05-27': 'GS FOUNDATION\nFoundation of Ancient & Medieval History 03\nNCERT',
  '2026-05-28': 'GS FOUNDATION\nFoundation of Ancient & Medieval History 04\nNCERT',
  '2026-05-29': 'GS FOUNDATION\nFoundation of Art and Culture 01\nNCERT',
  '2026-05-30': 'GS FOUNDATION\nFoundation of Art and Culture 02\nNCERT',
  '2026-05-31': 'GS SELF-STUDY (Sunday)\nAMH + Art & Culture revision',
  '2026-06-01': 'GS FOUNDATION\nFoundation of Modern Indian History 01\nNCERT',
  '2026-06-02': 'GS FOUNDATION\nFoundation of Modern Indian History 02\nNCERT',
  '2026-06-03': 'GS FOUNDATION\nFoundation of Modern Indian History 03\nNCERT',
  '2026-06-04': 'GS FOUNDATION\nFoundation of Modern Indian History 04\nNCERT',
  '2026-06-05': 'GS FOUNDATION\nFoundation of Modern Indian History 05\nNCERT',
  '2026-06-06': 'GS FOUNDATION\nFoundation of Modern Indian History 06\nNCERT',
  '2026-06-07': 'GS FOUNDATION\nFoundation of Economy 01\nNCERT',
  '2026-06-08': 'GS FOUNDATION\nFoundation of Economy 02\nNCERT',
  '2026-06-09': 'GS FOUNDATION\nFoundation of Economy 03\nNCERT',
  '2026-06-10': 'GS FOUNDATION\nFoundation of Economy 04\nNCERT',
  '2026-06-11': 'GS FOUNDATION\nFoundation of Economy 05\nNCERT',
  '2026-06-12': 'GS FOUNDATION\nFoundation of S&T 01\nNCERT',
  '2026-06-13': 'GS FOUNDATION\nFoundation of S&T 02\nNCERT',
  '2026-06-14': 'GS SELF-STUDY (Sunday)\nEconomy + S&T NCERT review',
  '2026-06-15': 'GS FOUNDATION\nFoundation of S&T 03\nNCERT',
  '2026-06-16': 'GS FOUNDATION\nFoundation of S&T 04\nNCERT',
  '2026-06-17': 'GS FOUNDATION\nFoundation of S&T 05\nNCERT',
  // PHASE 2: GS Basics (LIVE from Jun 18)
  '2026-06-18': 'GS BASICS (Live)\nIntroduction to GS Basics\n(7 PM Class)',
  '2026-06-19': 'GS BASICS\nStrategy, Planning & Consistency Session\n(7 PM Class)',
  '2026-06-20': 'GS SELF-STUDY\nFoundation NCERTs full revision\n(no class)',
  '2026-06-21': 'GS SELF-STUDY (Sunday)\nAll subjects NCERT notes\n+ MCQ practice',
  '2026-06-22': 'GS BASICS\nRoadmap for UPSC CSE\n(7 PM Class)',
  '2026-06-23': 'GS SELF-STUDY\nModern Indian History NCERT\n+ revision',
  '2026-06-24': 'GS SELF-STUDY\nAll Foundation material review\n+ question bank',
  '2026-06-25': 'GS BASICS\nModern Indian History 01\nAdvent of Europeans; decline of Mughals',
  '2026-06-26': 'GS BASICS\nModern Indian History 02\nConsolidation of British Power',
  '2026-06-27': 'GS BASICS\nModern Indian History 03\nPolicies of British; Civil Service evolution',
  '2026-06-28': 'GS SELF-STUDY (Sunday)\nMIH 01-03 consolidation notes',
  '2026-06-29': 'GS BASICS (10AM: How to prep CA)\nModern Indian History 04\nCivil & Tribal Uprisings; 1857',
  '2026-06-30': 'GS BASICS\nModern Indian History 05\nGovernor Generals; Socio-Religious Reforms',
  '2026-07-01': 'GS BASICS\nModern Indian History 06\nDevelopment of Press; Rise of Nationalism; INC',
  '2026-07-02': 'GS BASICS\nModern Indian History 07\nNational Movement 1905-18',
  '2026-07-03': 'GS BASICS\nModern Indian History 08\nEmergence of Gandhi',
  '2026-07-04': 'GS BASICS\nModern Indian History 09\nNational Movement 1920-29',
  '2026-07-05': 'GS SELF-STUDY (Sunday)\nMIH 06-09 revision + notes',
  '2026-07-06': 'GS BASICS (10AM: Weekly CA)\nModern Indian History 10\nSimon Commission to Poona Pact',
  '2026-07-07': 'GS BASICS (4PM + 7PM)\nMIH 11: National Movement 1934-42\nMIH 12: Towards Freedom; Misc',
  '2026-07-08': 'GS BASICS (4PM + 7PM)\nMIH 13: Modern History Buffer\nMIH 14: Modern History Buffer',
  '2026-07-09': 'GS BASICS\nEnvironment & Ecology 01\nIntroduction & Strategy',
  '2026-07-10': 'GS BASICS\nEnvironment & Ecology 02\nEcology – Basic Concepts',
  '2026-07-11': 'GS BASICS\nEnvironment & Ecology 03\nEcology – Principles & Functions',
  '2026-07-12': 'GS SELF-STUDY (Sunday)\nEnvironment: E&E 01-03 consolidation',
  '2026-07-13': 'GS BASICS (10AM: Weekly CA)\nEnvironment & Ecology 04\nBiodiversity',
  '2026-07-14': 'GS BASICS\nEnvironment & Ecology 05\nConservation of Biodiversity',
  '2026-07-15': 'GS BASICS\nEnvironment & Ecology 06\nPollution – Part 01',
  '2026-07-16': 'GS BASICS\nEnvironment & Ecology 07\nPollution – Part 02',
  '2026-07-17': 'GS BASICS\nEnvironment & Ecology 08\nClimate Change – Global Warming',
  '2026-07-18': 'GS BASICS\nEnvironment & Ecology 09\nClimate Change – Organisations',
  '2026-07-19': 'GS SELF-STUDY (Sunday)\nE&E 04-09 revision + notes',
  '2026-07-20': 'GS BASICS (10AM: Weekly CA)\nEnvironment & Ecology 10\nImportant Acts & Policies',
  '2026-07-21': 'GS BASICS\nEnvironment & Ecology 11\nInternational Conventions',
  '2026-07-22': 'GS BASICS\nEnvironment & Ecology 12\nEnvironmental Impact Assessment',
  '2026-07-23': 'GS BASICS\nIndian Polity 01\nIntroduction + Concepts & Terminologies',
  '2026-07-24': 'GS BASICS\nIndian Polity 02\nHistorical underpinnings; Making of Constitution',
  '2026-07-25': 'GS BASICS\nIndian Polity 03\nPreamble; Union of India; Citizenship',
  '2026-07-26': 'GS SELF-STUDY (Sunday)\nPolity 01-03 + E&E full revision',
  '2026-07-27': 'GS BASICS (10AM: Weekly CA)\nIndian Polity 04\nFundamental Rights',
  '2026-07-28': 'GS BASICS\nIndian Polity 05\nFundamental Duties & DPSP',
  '2026-07-29': 'GS BASICS\nIndian Polity 06\nAmendments & Basic Structure',
  '2026-07-30': 'GS BASICS\nIndian Polity 07\nPresident & Governor',
  '2026-07-31': 'GS BASICS\nIndian Polity 08\nPM & Parliament Part 1',
  '2026-08-01': 'GS BASICS\nIndian Polity 09\nParliament Part 2',
  '2026-08-02': 'GS SELF-STUDY (Sunday)\nPolity 04-09 revision + notes',
  '2026-08-03': 'GS BASICS (10AM: Weekly CA)\nIndian Polity 10\nEmergency Provisions',
  '2026-08-04': 'GS BASICS\nIndian Polity 11\nJudiciary Part 1',
  '2026-08-05': 'GS BASICS\nIndian Polity 12\nJudiciary Part 2',
  '2026-08-06': 'GS BASICS (4PM + 7PM)\nPolity 13: Local Governance\nPolity 14: Elections & Misc',
  '2026-08-07': 'GS BASICS (4PM + 7PM)\nIndian Polity 15: Buffer\nIndian Polity 16: Buffer',
  '2026-08-08': 'GS BASICS\nGeography 01\nIntro – Basics of Map as tool',
  '2026-08-09': 'GS SELF-STUDY (Sunday)\nPolity 10-16 revision; Geography prep',
  '2026-08-10': 'GS BASICS (10AM: Weekly CA)\nGeography 02\nPhysical Geography – Landforms',
  '2026-08-11': 'GS BASICS\nGeography 03\nClimatology Part 01',
  '2026-08-12': 'GS BASICS\nGeography 04\nClimatology Part 02',
  '2026-08-13': 'GS BASICS\nGeography 05\nPhysical Geography of India Part 01',
  '2026-08-14': 'GS BASICS (4PM + 7PM)\nGeography 06: Physical Geog India 02\nGeography 07: Physical Geog India 03',
  '2026-08-15': 'INDEPENDENCE DAY (Holiday)\nLight revision: Geography notes\n+ current affairs',
  '2026-08-16': 'GS SELF-STUDY (Sunday)\nGeography 01-07 revision + maps',
  '2026-08-17': 'GS BASICS (10AM: Weekly CA)\nGeography 08\nHuman Geography Part 01',
  '2026-08-18': 'GS BASICS\nGeography 09\nHuman Geography Part 02',
  '2026-08-19': 'GS BASICS (4PM + 7PM)\nGeography 10: Human Geog India 01\nGeography 11: Human Geog India 02',
  '2026-08-20': 'GS BASICS (4PM + 7PM)\nGeography 12: Human Geog India 03\nGeography 13: Buffer',
  '2026-08-21': 'GS BASICS (4PM + 7PM)\nGeography 14: Buffer\nGeography 15: Buffer',
  '2026-08-22': 'GS BASICS\nScience & Technology 01\nSpace Technology Part 1',
  '2026-08-23': 'GS SELF-STUDY (Sunday)\nGeography full revision + maps',
  '2026-08-24': 'GS BASICS (10AM: Weekly CA)\nScience & Technology 02\nSpace Technology Part 2',
  '2026-08-25': 'GS BASICS\nScience & Technology 03\nBiotechnology & Genetic Engineering 01',
  '2026-08-26': 'GS BASICS\nScience & Technology 04\nBiotechnology & Genetic Engineering 02',
  '2026-08-27': 'GS BASICS\nScience & Technology 05\nBiofuels; Energy Technologies; Nuclear',
  '2026-08-28': 'GS BASICS\nScience & Technology 06\nNanotechnology',
  '2026-08-29': 'GS BASICS\nScience & Technology 07\nHealth & Disease Part 01',
  '2026-08-30': 'GS SELF-STUDY (Sunday)\nS&T 01-07 revision + notes',
  '2026-08-31': 'GS BASICS (10AM: Weekly CA)\nScience & Technology 08\nHealth & Disease Part 02',
  '2026-09-01': 'GS BASICS (4PM + 7PM)\nS&T 09: Computer & Comms Technology\nS&T 10: Robotics & AI',
  '2026-09-02': 'GS BASICS (4PM + 7PM)\nS&T 11: Miscellaneous Topics\nS&T 12: Miscellaneous Topics',
  '2026-09-03': 'GS BASICS\nEconomy 01\nIntroduction to Economics',
  '2026-09-04': 'GS BASICS\nEconomy 02\nNational Income Accounting',
  '2026-09-05': 'GS BASICS\nEconomy 03\nGrowth; Development; Inequality; Poverty',
  '2026-09-06': 'GS SELF-STUDY (Sunday)\nEconomy + S&T revision',
  '2026-09-07': 'GS BASICS (10AM: Weekly CA)\nEconomy 04\nMoney & Inflation',
  '2026-09-08': 'GS BASICS\nEconomy 05\nMonetary Policy',
  '2026-09-09': 'GS BASICS\nEconomy 06\nPublic Finance',
  '2026-09-10': 'GS BASICS\nEconomy 07\nTaxation',
  '2026-09-11': 'GS BASICS\nEconomy 08\nBanking',
  '2026-09-12': 'GS BASICS\nEconomy 09\nFinancial Market',
  '2026-09-13': 'GS SELF-STUDY (Sunday)\nEconomy 01-09 revision',
  '2026-09-14': 'GS BASICS (10AM: Weekly CA)\nEconomy 10\nExternal Sector',
  '2026-09-15': 'GS BASICS (4PM + 7PM)\nEconomy 11: International Orgs\nEconomy 12: Planning; Unemployment',
  '2026-09-16': 'GS BASICS (4PM + 7PM)\nEconomy 13: Buffer\nEconomy 14: Buffer',
  '2026-09-17': 'GS BASICS\nAncient & Medieval History 01\nIntroduction; Pre-historic period',
  '2026-09-18': 'GS BASICS\nAncient & Medieval History 02\nIndus Valley Civilisation',
  '2026-09-19': 'GS BASICS\nAncient & Medieval History 03\nVedic age; Jainism; Buddhism',
  '2026-09-20': 'GS SELF-STUDY (Sunday)\nAMH 01-03 + Economy full revision',
  '2026-09-21': 'GS BASICS (10AM: Weekly CA)\nAncient & Medieval History 04\nMauryan age; Persian invasion',
  '2026-09-22': 'GS BASICS\nAncient & Medieval History 05\nPost-Mauryan; Sangam Age',
  '2026-09-23': 'GS BASICS\nAncient & Medieval History 06\nGupta; Post-Gupta; Harshavardhan',
  '2026-09-24': 'GS BASICS\nAncient & Medieval History 07\nTripartite Struggle; Arab invasions',
  '2026-09-25': 'GS BASICS\nAncient & Medieval History 08\nCholas; Delhi Sultanate',
  '2026-09-26': 'GS BASICS\nAncient & Medieval History 09\nMughal Part 1',
  '2026-09-27': 'GS SELF-STUDY (Sunday)\nAMH 04-09 revision + notes',
  '2026-09-28': 'GS BASICS (10AM: Weekly CA)\nAncient & Medieval History 10\nMughal Part 2; Vijayanagar',
  '2026-09-29': 'GS BASICS (4PM + 7PM)\nAMH 11: Bhakti; Maratha Empire\nAMH 12: Misc Art & Culture',
  '2026-09-30': 'GS BASICS (4PM + 7PM)\nAMH 13: Buffer lecture\nAMH 14: Buffer lecture',
  // PHASE 3: GS Advance Phase 1 (Oct 1 – Dec 31, 2026)
  '2026-10-01': 'GS ADVANCE P1 (4PM + 7PM)\nIntro to GS Advance\nIndian Society 01: Salient features; Diversity',
  '2026-10-02': 'GS ADVANCE\nIndian Society 02\nSalient features; Diversity Part 02',
  '2026-10-03': 'GS ADVANCE\nIndian Society 03\nRole of Women; Population issues',
  '2026-10-04': 'GS SELF-STUDY (Sunday)\nSociety 01-03 + AMH full revision',
  '2026-10-05': 'GS ADVANCE (10AM: Weekly CA)\nIndian Society 04\nPoverty; Urbanization; Remedies',
  '2026-10-06': 'GS ADVANCE\nIndian Society 05\nGlobalization effects Part 01',
  '2026-10-07': 'GS ADVANCE\nIndian Society 06\nGlobalization effects Part 02',
  '2026-10-08': 'GS ADVANCE\nIndian Society 07\nSocial Empowerment Part 01',
  '2026-10-09': 'GS ADVANCE (4PM + 7PM)\nSociety 08: Social Empowerment P02\nSociety 09: PYQs Live Writing',
  '2026-10-10': 'GS ADVANCE\nPost-Independence History 01\nConsolidation & Reorganization Part 01',
  '2026-10-11': 'GS SELF-STUDY (Sunday)\nSociety + Post-Ind History revision',
  '2026-10-12': 'GS ADVANCE (10AM: Weekly CA)\nPost-Independence History 02\nConsolidation Part 02',
  '2026-10-13': 'GS ADVANCE\nWorld History 01\nIndustrial Revolution; World Wars',
  '2026-10-14': 'GS ADVANCE\nWorld History 02\nRedrawal of boundaries; Colonization',
  '2026-10-15': 'GS ADVANCE\nWorld History 03\nDecolonization; Political philosophies',
  '2026-10-16': 'GS ADVANCE (4PM + 7PM)\nWorld History 04\nWorld History + PIH PYQs',
  '2026-10-17': 'GS ADVANCE\nEssay Session 01\nWriting to think',
  '2026-10-18': 'GS SELF-STUDY (Sunday)\nWorld History + Essay practice',
  '2026-10-19': 'GS ADVANCE (10AM: Weekly CA)\nEssay Session 02\nIntro & Conclusion writing',
  '2026-10-20': 'GS ADVANCE\nGovernance 01\nGovernance; transparency; accountability Part 01',
  '2026-10-21': 'GS ADVANCE\nGovernance 02\nGovernance Part 02; e-governance',
  '2026-10-22': 'GS ADVANCE\nGovernance 03\nGovernance Part 03; models',
  '2026-10-23': 'GS ADVANCE\nGovernance 04\nCitizen charters; transparency',
  '2026-10-24': 'GS ADVANCE\nGovernance 05\nRole of civil services in democracy',
  '2026-10-25': 'GS SELF-STUDY (Sunday)\nGovernance 01-05 revision + notes',
  '2026-10-26': 'GS ADVANCE (10AM: Weekly CA)\nGovernance 06\nPYQs – Live Answer Writing Session',
  '2026-10-27': 'GS ADVANCE\nSocial Justice 01\nGovernment policies & development',
  '2026-10-28': 'GS ADVANCE\nSocial Justice 02\nNGOs; SHGs; development industry',
  '2026-10-29': 'GS ADVANCE\nSocial Justice 03\nWelfare schemes; vulnerable sections',
  '2026-10-30': 'GS ADVANCE\nSocial Justice 04\nHealth; Education; Human Resources',
  '2026-10-31': 'GS ADVANCE\nSocial Justice 05\nPoverty & hunger issues',
  '2026-11-01': 'GS SELF-STUDY (Sunday)\nSocial Justice revision',
  '2026-11-02': 'GS ADVANCE (10AM: Weekly CA)\nSocial Justice 06\nPYQs – Live Answer Writing',
  '2026-11-03': 'GS ADVANCE\nInternational Relations 01\nIndia & neighborhood Part 01',
  '2026-11-04': 'GS ADVANCE\nInternational Relations 02\nIndia & neighborhood Part 02',
  '2026-11-05': 'GS ADVANCE (4PM + 7PM)\nIR 03: Regional groupings\nIR 04: Bilateral agreements',
  '2026-11-06': 'DIWALI BREAK (Nov 6-11)\nLight revision: IR notes\n+ Current affairs',
  '2026-11-07': 'DIWALI BREAK\nLight reading: Newspaper\n+ optional revision',
  '2026-11-08': 'DIWALI BREAK\nLight reading: IR topics\n+ rest & recovery',
  '2026-11-09': 'DIWALI BREAK\nLight revision: essay outlines\n+ current affairs catchup',
  '2026-11-10': 'DIWALI BREAK\nLight reading: GS notes\n+ CA review',
  '2026-11-11': 'DIWALI BREAK\nLight reading: newspaper\n+ Odia writing practice',
  '2026-11-12': 'GS ADVANCE\nIR 06: Developed/developing countries P02\n(7 PM Class)',
  '2026-11-13': 'GS ADVANCE\nIR 07: International institutions Part 01\n(7 PM Class)',
  '2026-11-14': 'GS ADVANCE (4PM + 7PM)\nIR 08: International institutions P02\nIR 09: PYQs Writing Session',
  '2026-11-15': 'GS SELF-STUDY (Sunday)\nIR full revision + notes',
  '2026-11-16': 'GS ADVANCE (10AM: Weekly CA)\nEssay Session 03\nExploration / Body writing',
  '2026-11-17': 'GS ADVANCE (4PM + 7PM)\nEssay Session 04: Essay Editing\nAgriculture 01: Crops; irrigation',
  '2026-11-18': 'GS ADVANCE (4PM + 7PM)\nAgriculture 02: Storage; transport; e-tech\nAgriculture 03: Subsidies; MSP; PDS',
  '2026-11-19': 'GS ADVANCE (4PM + 7PM)\nAgriculture 04: Food processing\nAgriculture 05: PYQs Writing',
  '2026-11-20': 'GS ADVANCE\nDisaster Management 01\n(7 PM Class)',
  '2026-11-21': 'GS ADVANCE (4PM + 7PM)\nDisaster Management 02\nDM 03: PYQs Writing Session',
  '2026-11-22': 'GS SELF-STUDY (Sunday)\nAgriculture + DM revision',
  '2026-11-23': 'GS ADVANCE (10AM: Weekly CA)\nInternal Security 01\nLinkages: development & extremism',
  '2026-11-24': 'GS ADVANCE\nInternal Security 02\nExternal state & non-state actors',
  '2026-11-25': 'GS ADVANCE\nInternal Security 03\nCommunication networks; cyber security',
  '2026-11-26': 'GS ADVANCE\nInternal Security 04\nMoney laundering & prevention',
  '2026-11-27': 'GS ADVANCE\nInternal Security 05\nBorder security; organized crime',
  '2026-11-28': 'GS ADVANCE (4PM + 7PM)\nInternal Security 06: Security forces\nIS 07: PYQs Writing Session',
  '2026-11-29': 'GS SELF-STUDY (Sunday)\nInternal Security revision',
  '2026-11-30': 'GS ADVANCE (10AM: Weekly CA)\nEthics Theory 01\nBasics of Ethics; what is ethics',
  '2026-12-01': 'GS ADVANCE\nEthics Theory 02\nEssence; determinants; Western & Indian ethics',
  '2026-12-02': 'GS ADVANCE\nEthics Theory 03\nImportant theories & principles',
  '2026-12-03': 'GS ADVANCE\nEthics Theory 04\nFour Branches of Ethics; Public-Private life',
  '2026-12-04': 'GS ADVANCE\nEthics Theory 05\nHuman values; educational role',
  '2026-12-05': 'GS ADVANCE\nEthics Theory 06\nLessons from great leaders & reformers',
  '2026-12-06': 'GS SELF-STUDY (Sunday)\nEthics 01-06 revision + notes',
  '2026-12-07': 'GS ADVANCE (10AM: Weekly CA)\nEthics Theory 07\nAttitude – content; structure; function',
  '2026-12-08': 'GS ADVANCE\nEthics Theory 08\nMoral & political attitudes; persuasion',
  '2026-12-09': 'GS ADVANCE\nEthics Theory 09\nAptitude & values for Civil Service',
  '2026-12-10': 'GS ADVANCE\nEthics Theory 10\nEmotional Intelligence in governance',
  '2026-12-11': 'GS ADVANCE\nEthics Theory 11\nMoral thinkers (India & world)',
  '2026-12-12': 'GS ADVANCE\nEthics Theory 12\nPublic service values; ethics in PA',
  '2026-12-13': 'GS SELF-STUDY (Sunday)\nEthics 07-12 revision',
  '2026-12-14': 'GS ADVANCE (10AM: Weekly CA)\nEthics Theory 13\nEthical concerns & dilemmas',
  '2026-12-15': 'GS SELF-STUDY\nEthics buffer / catch up day',
  '2026-12-16': 'GS ADVANCE\nEthics Theory 14\nSources of ethical guidance',
  '2026-12-17': 'GS ADVANCE\nEthics Theory 15\nAccountability; ethical governance; IR ethics',
  '2026-12-18': 'GS ADVANCE (4PM + 7PM)\nEthics Theory 16: Probity in Governance\nEthics Theory 17: Work culture',
  '2026-12-19': 'GS ADVANCE (4PM + 7PM)\nEthics Theory 18: Applied Ethics + PYQs\nEthics Theory 19: PYQs Writing',
  '2026-12-20': 'GS SELF-STUDY (Sunday)\nEthics 13-19 revision',
  '2026-12-21': 'GS ADVANCE (10AM: Weekly CA)\nEthics Theory 20\nPYQs Live Answer Writing',
  '2026-12-22': 'GS ADVANCE\nEthics Case Study 01\nCase study analysis',
  '2026-12-23': 'GS ADVANCE\nEthics Case Study 02\nCase study analysis',
  '2026-12-24': 'GS ADVANCE\nEthics Case Study 03\nCase study analysis',
  '2026-12-25': 'GS ADVANCE\nEthics Case Study 04\nCase study analysis',
  '2026-12-26': 'GS ADVANCE\nEthics Case Study 05\nCase study analysis',
  '2026-12-27': 'GS SELF-STUDY (Sunday)\nEthics comprehensive revision',
  '2026-12-28': 'GS ADVANCE (10AM: Weekly CA)\nEthics Case Study 06\nCase study analysis',
  '2026-12-29': 'GS ADVANCE (4PM + 7PM)\nEthics Case Study 07: PYQs Writing\nEssay Test Discussion Part 1',
  '2026-12-30': 'GS ADVANCE\nEssay Test Discussion Part 2\nEssay brainstorming session',
  '2026-12-31': 'GS BUFFER / REVIEW\nAll GS Advance Phase 1 revision\n+ notes consolidation',
  // PHASE 4: Prelims Focus (Jan 4 – Apr 24, 2027)
  '2027-01-01': 'GS NEW YEAR BUFFER\nAll subjects revision\n+ study plan review',
  '2027-01-02': 'GS BUFFER\nWeak topics revision\n+ notes making',
  '2027-01-03': 'GS BUFFER (Sunday)\nMCQ practice – all subjects\n+ test plan review',
  '2027-01-04': 'PRELIMS SIP (10AM: Weekly CA)\nIntroduction to Prelims SIP\nStrategy & approach',
  '2027-01-05': 'PRELIMS\nIndian Polity PPQs 01\nHistorical background; Making of Const',
  '2027-01-06': 'PRELIMS\nIndian Polity PPQs 02\nUnion; Citizenship; Fundamental Rights',
  '2027-01-07': 'PRELIMS\nIndian Polity PPQs 03\nDPSP; Fundamental Duties; Amendment',
  '2027-01-08': 'PRELIMS\nIndian Polity PPQs 04\nPresident; Governor; Emergency',
  '2027-01-09': 'PRELIMS\nIndian Polity PPQs 05\nParliamentary System; Parliament',
  '2027-01-10': 'GS SELF-STUDY (Sunday)\nPolity PPQs 01-05 revision',
  '2027-01-11': 'PRELIMS (10AM: Weekly CA)',
  '2027-01-12': 'PRELIMS\nIndian Polity PPQs 06\nParliamentary Committees; CAG; Supreme Court',
  '2027-01-13': 'PRELIMS\nIndian Polity PPQs 07\nHigh Court; Federal System; State Legislature',
  '2027-01-14': 'PRELIMS\nIndian Polity PPQs 08\nSpecial provisions; Panchayati Raj (73rd); UTs',
  '2027-01-15': 'PRELIMS\nIndian Polity PPQs 09\nConstitutional & Statutory Bodies',
  '2027-01-16': 'PRELIMS\nIndian Polity PPQs 10\nPolitical parties; Elections; Anti-defection',
  '2027-01-17': 'GS SELF-STUDY (Sunday)\nPolity PPQs 06-10 + full revision',
  '2027-01-18': 'PRELIMS (10AM: Weekly CA)',
  '2027-01-19': 'PRELIMS\nModern Indian History PPQs 01\nAdvent of Europeans; Regional States',
  '2027-01-20': 'PRELIMS\nModern Indian History PPQs 02\nConsolidation of British',
  '2027-01-21': 'PRELIMS\nModern Indian History PPQs 03\nConstitutional development; Land revenue',
  '2027-01-22': 'PRELIMS\nModern Indian History PPQs 04\nCivil & Tribal Uprisings; 1857',
  '2027-01-23': 'PRELIMS\nModern Indian History PPQs 05\nSocio-Religious Reforms',
  '2027-01-24': 'GS SELF-STUDY (Sunday)\nMIH PPQs 01-05 revision',
  '2027-01-25': 'PRELIMS (10AM: Weekly CA)\nCSAT Lecture 01: Intro to CSAT',
  '2027-01-26': 'PRELIMS\nModern Indian History PPQs 06\nNationalism; INC formation; Moderate phase',
  '2027-01-27': 'PRELIMS\nCSAT Lecture 02: Reading Comprehension 01\nMIH PPQs 07: 1907-18 National Movement',
  '2027-01-28': 'PRELIMS\nCSAT Lecture 03: Reading Comprehension 02\nMIH PPQs 08: Gandhi; 1919-27',
  '2027-01-29': 'PRELIMS\nModern Indian History PPQs 09\nNational Movement 1928-40',
  '2027-01-30': 'PRELIMS\nModern Indian History PPQs 10\nNational Movement 1941-47; Misc',
  '2027-01-31': 'GS SELF-STUDY (Sunday)\nMIH full PPQs revision',
  '2027-02-01': 'PRELIMS (10AM: Weekly CA)\nCSAT Lecture 04: RC 03',
  '2027-02-02': 'PRELIMS\nCSAT Lecture 05: RC 04\nAncient Medieval PPQs 01: Indus; Pre-history',
  '2027-02-03': 'PRELIMS\nCSAT Lecture 06: RC 05\nAncient Medieval PPQs 02: Vedic; Jainism',
  '2027-02-04': 'PRELIMS\nCSAT Lecture 07: RC 06\nAncient Medieval PPQs 03: Mauryan age',
  '2027-02-05': 'PRELIMS\nAncient Medieval PPQs 04\nGupta – Post-Gupta',
  '2027-02-06': 'PRELIMS\nAncient Medieval PPQs 05\nTripartite struggle; Rajputs',
  '2027-02-07': 'GS SELF-STUDY (Sunday)\nAMH PPQs 01-05 revision',
  '2027-02-08': 'PRELIMS (10AM: Weekly CA)\nCSAT Lecture 08: RC 07',
  '2027-02-09': 'PRELIMS\nCSAT Lecture 09: RC 08\nAncient Medieval PPQs 06: Cholas; Delhi Sultanate',
  '2027-02-10': 'PRELIMS\nCSAT Lecture 10: RC 09\nAncient Medieval PPQs 07: Vijayanagar; Maratha',
  '2027-02-11': 'PRELIMS\nCSAT Lecture 11: RC 10\nAMH PPQs 08: Bhakti; Architecture',
  '2027-02-12': 'PRELIMS\nAncient Medieval PPQs 09\nVisual arts; Paintings; Literature',
  '2027-02-13': 'PRELIMS\nAncient Medieval PPQs 10\nPerforming Arts; Intangible Heritage',
  '2027-02-14': 'GS SELF-STUDY (Sunday)\nAMH full PPQs + Art & Culture revision',
  '2027-02-15': 'PRELIMS (10AM: Weekly CA)\nCSAT Lecture 12: RC 11',
  '2027-02-16': 'PRELIMS\nCSAT Lecture 13: RC 12',
  '2027-02-17': 'PRELIMS\nCSAT Lecture 14: Maths & Reasoning 01\nGeography PPQs 01: Earth; Landforms',
  '2027-02-18': 'PRELIMS\nCSAT Lecture 15: Maths & Reasoning 02\nGeography PPQs 02: Geomorphic processes',
  '2027-02-19': 'PRELIMS\nGeography PPQs 03\nClimatology; Atmosphere',
  '2027-02-20': 'PRELIMS\nGeography PPQs 04\nAtmospheric circulation; Climate change',
  '2027-02-21': 'PRELIMS (Sunday)\nGeography PPQs 05\nWater; Oceans; Biodiversity',
  '2027-02-22': 'PRELIMS (10AM: Weekly CA)\nCSAT Lecture 16: Maths & Reasoning 03',
  '2027-02-23': 'PRELIMS\nCSAT Lecture 17: M&R 04\nGeography PPQs 06: India – Location; Drainage',
  '2027-02-24': 'PRELIMS\nCSAT Lecture 18: M&R 05\nGeography PPQs 07: India Climate; Vegetation',
  '2027-02-25': 'PRELIMS\nCSAT Lecture 19: M&R 06\nGeography PPQs 08: Human Geography',
  '2027-02-26': 'PRELIMS\nGeography PPQs 09\n12th NCERT: India People & Economy',
  '2027-02-27': 'PRELIMS\nGeography PPQs 10\nMapping; Map-based questions',
  '2027-02-28': 'GS SELF-STUDY (Sunday)\nGeography full PPQs revision',
  '2027-03-01': 'PRELIMS (10AM: Weekly CA)\nCSAT Lecture 20: M&R 07',
  '2027-03-02': 'PRELIMS\nCSAT Lecture 21: M&R 08\nS&T PPQs 01: Basics Chemistry & Physics',
  '2027-03-03': 'PRELIMS\nCSAT Lecture 22: M&R 09\nS&T PPQs 02: Basics Biology',
  '2027-03-04': 'PRELIMS\nCSAT Lecture 23: M&R 10\nS&T PPQs 03: Space Technology',
  '2027-03-05': 'PRELIMS\nS&T PPQs 04\nBiotechnology & Genetic Engineering',
  '2027-03-06': 'PRELIMS\nS&T PPQs 05\nBiofuels; Energy; Nuclear',
  '2027-03-07': 'GS SELF-STUDY (Sunday)\nS&T PPQs 01-05 revision',
  '2027-03-08': 'PRELIMS (10AM: Weekly CA)\nCSAT Lecture 24: M&R 11',
  '2027-03-09': 'PRELIMS\nCSAT Lecture 25: M&R 12\nS&T PPQs 06: Nano; Health & Disease',
  '2027-03-10': 'PRELIMS\nCSAT Lecture 26: M&R 13\nS&T PPQs 07: Computers; Robotics; IT',
  '2027-03-11': 'PRELIMS\nCSAT Lecture 27: M&R 14\nS&T PPQs 08: Artificial Intelligence',
  '2027-03-12': 'PRELIMS\nS&T PPQs 09: Defence Technology',
  '2027-03-13': 'PRELIMS\nS&T PPQs 10: Miscellaneous Topics in News',
  '2027-03-14': 'GS SELF-STUDY (Sunday)\nS&T full PPQs revision',
  '2027-03-15': 'PRELIMS (10AM: Weekly CA)\nCSAT Lecture 28: M&R 15',
  '2027-03-16': 'PRELIMS\nCSAT Lecture 29: M&R 16\nE&E PPQs 01: Ecology – Basic Concepts',
  '2027-03-17': 'PRELIMS\nCSAT Lecture 30: M&R 17\nE&E PPQs 02: Ecology – Principles',
  '2027-03-18': 'PRELIMS\nCSAT Lecture 31: M&R 18\nE&E PPQs 03: Biodiversity',
  '2027-03-19': 'PRELIMS\nE&E PPQs 04: Conservation of Biodiversity',
  '2027-03-20': 'PRELIMS\nE&E PPQs 05: Pollution – Air, Water, Soil',
  '2027-03-21': 'GS SELF-STUDY (Sunday)\nE&E PPQs 01-05 revision',
  '2027-03-22': 'PRELIMS (10AM: Weekly CA)\nCSAT Lecture 32: M&R 19',
  '2027-03-23': 'PRELIMS\nCSAT Lecture 33: M&R 20\nE&E PPQs 06: Climate Change',
  '2027-03-24': 'PRELIMS\nCSAT Lecture 34: M&R 21\nE&E PPQs 07: Acts & Policies',
  '2027-03-25': 'PRELIMS\nCSAT Lecture 35: M&R 22\nE&E PPQs 08: International Organisations',
  '2027-03-26': 'PRELIMS\nE&E PPQs 09: International Conventions',
  '2027-03-27': 'PRELIMS\nE&E PPQs 10: Protected areas; Species in news',
  '2027-03-28': 'GS SELF-STUDY (Sunday)\nE&E full PPQs revision',
  '2027-03-29': 'PRELIMS (10AM: Weekly CA)\nCSAT Lecture 36: M&R 23',
  '2027-03-30': 'PRELIMS\nCSAT Lecture 37: M&R 24\nEconomy PPQs 01: Introduction',
  '2027-03-31': 'PRELIMS\nCSAT Lecture 38: M&R 25\nEconomy PPQs 02: National Income; Development',
  '2027-04-01': 'PRELIMS\nCSAT Lecture 39: M&R 26\nEconomy PPQs 03: Money & Inflation',
  '2027-04-02': 'PRELIMS\nEconomy PPQs 04: Monetary Policy; Public Finance',
  '2027-04-03': 'PRELIMS\nEconomy PPQs 05: Taxation',
  '2027-04-04': 'GS SELF-STUDY (Sunday)\nEconomy PPQs 01-05 revision',
  '2027-04-05': 'PRELIMS (10AM: Weekly CA)\nCSAT Lecture 40: M&R 27',
  '2027-04-06': 'PRELIMS\nCSAT Lecture 41: M&R 28\nEconomy PPQs 06: Banking',
  '2027-04-07': 'PRELIMS\nCSAT Lecture 42: M&R 29\nEconomy PPQs 07: Financial Market; Agriculture',
  '2027-04-08': 'PRELIMS\nCSAT Lecture 43: M&R 30\nEconomy PPQs 08: Industry; Infrastructure',
  '2027-04-09': 'PRELIMS\nEconomy PPQs 09: External Sector; Intl Orgs',
  '2027-04-10': 'PRELIMS\nEconomy PPQs 10: Planning; Unemployment; HRD',
  '2027-04-11': 'GS SELF-STUDY (Sunday)\nEconomy full PPQs revision',
  '2027-04-12': 'PRELIMS (10AM: Weekly CA)',
  '2027-04-13': 'PRELIMS\nCSAT: Comprehension PPQs 01\nLanguage Comprehension practice',
  '2027-04-14': 'PRELIMS\nCSAT: Comprehension PPQs 02\nLanguage Comprehension practice',
  '2027-04-15': 'PRELIMS\nCSAT: Comprehension PPQs 03\nLanguage Comprehension practice',
  '2027-04-16': 'PRELIMS\nCSAT: Comprehension PPQs 04\nLanguage Comprehension practice',
  '2027-04-17': 'PRELIMS\nCSAT: Comprehension PPQs 05\nLanguage Comprehension practice',
  '2027-04-18': 'GS SELF-STUDY (Sunday)\nCSAT Comprehension full revision',
  '2027-04-19': 'PRELIMS (10AM: Weekly CA)',
  '2027-04-20': 'PRELIMS\nReasoning + Aptitude PPQs 01\nLogical Reasoning + Aptitude',
  '2027-04-21': 'PRELIMS\nReasoning + Aptitude PPQs 02\nLogical Reasoning + Aptitude',
  '2027-04-22': 'PRELIMS\nReasoning + Aptitude PPQs 03\nLogical Reasoning + Aptitude',
  '2027-04-23': 'PRELIMS\nReasoning + Aptitude PPQs 04\nLogical Reasoning + Aptitude',
  '2027-04-24': 'PRELIMS\nReasoning + Aptitude PPQs 05 (FINAL)\nPrelims SIP Phase Complete',
  // PRELIMS REVISION (Apr 25 – May 31, 2027)
  // Phase 5: GS Advance Phase 2 (Jun 1 – Aug 2027)
  '2027-06-01': 'GS ADVANCE P2\nMains Strategy Session\n(7 PM – Post-Prelims)',
  '2027-06-02': 'GS ADVANCE P2\nGS1 Modern Indian History 01\nSignificant events 18th c–present',
  '2027-06-03': 'GS ADVANCE P2\nGS1 Modern Indian History 02\nPersonalities of Modern India',
  '2027-06-04': 'GS ADVANCE P2\nGS1 Modern Indian History 03\nIssues in Modern India',
  '2027-06-05': 'GS ADVANCE P2\nGS1 Modern Indian History 04\nFreedom Struggle – stages; contributions Part 01',
  '2027-06-06': 'GS SELF-STUDY (Sunday)',
  '2027-06-07': 'GS ADVANCE P2\nGS1 Modern Indian History 05\nFreedom Struggle Part 02',
  '2027-06-08': 'GS ADVANCE P2\nGS1 Modern Indian History 06\nFreedom Struggle Part 03',
  '2027-06-09': 'GS ADVANCE P2\nGS1 Modern Indian History 07\nFreedom Struggle Part 04',
  '2027-06-10': 'GS ADVANCE P2\nGS1 Modern Indian History 08\nBuffer lecture',
  '2027-06-11': 'GS ADVANCE P2\nGS1 Modern Indian History 09\nPYQs – Live Answer Writing',
  '2027-06-12': 'GS REVISION\nModern History revision break',
  '2027-06-13': 'GS SELF-STUDY (Sunday)',
  '2027-06-14': 'GS ADVANCE P2\nGS1 Art & Culture 01\nArt Forms; Literature; Architecture 01',
  '2027-06-15': 'GS ADVANCE P2\nGS1 Art & Culture 02\nArt Forms; Literature; Architecture 02',
  '2027-06-16': 'GS ADVANCE P2\nGS1 Art & Culture 03\nArt Forms Part 03',
  '2027-06-17': 'GS ADVANCE P2\nGS1 Art & Culture 04\nArt Forms Part 04',
  '2027-06-18': 'GS ADVANCE P2\nGS1 Art & Culture 05\nArt Forms Part 05',
  '2027-06-19': 'GS ADVANCE P2\nGS1 Art & Culture 06\nPYQs – Answer Writing Practice',
  '2027-06-20': 'GS SELF-STUDY (Sunday)',
  '2027-06-21': 'GS ADVANCE P2\nGS1 Geography 01\nWorld Physical Geography 01',
  '2027-06-22': 'GS ADVANCE P2\nGS1 Geography 02\nWorld Physical Geography 02',
  '2027-06-23': 'GS ADVANCE P2\nGS1 Geography 03\nWorld Physical Geography 03',
  '2027-06-24': 'GS ADVANCE P2\nGS1 Geography 04\nNatural resources distribution 01',
  '2027-06-25': 'GS ADVANCE P2\nGS1 Geography 05\nNatural resources distribution 02',
  '2027-06-26': 'GS ADVANCE P2\nGS1 Geography 06\nFactors for industry location',
  '2027-06-27': 'GS SELF-STUDY (Sunday)',
  '2027-06-28': 'GS ADVANCE P2\nGS1 Geography 07\nGeophysical phenomena (EQ; Tsunami; Volcanic)',
  '2027-06-29': 'GS ADVANCE P2\nGS1 Geography 08\nGeographical features; Water bodies; Flora/Fauna',
  '2027-06-30': 'GS ADVANCE P2\nGS1 Geography 09\nPYQs – Answer Writing Practice',
};

// ─── BUILD ALL DAYS ───────────────────────────────────────────────────────────
function dateStr(y, m, d) {
  return `${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`;
}

function dayLabel(y, m, d) {
  const date = new Date(y, m-1, d);
  return `${DAYS[date.getDay()]}\n${d} ${MONTHS[m]} ${y}`;
}

// Math day counter: Day 1 = May 4, 2026
function mathDay(y, m, d) {
  const start = new Date(2026, 4, 4); // May 4, 2026
  const cur = new Date(y, m-1, d);
  const diff = Math.floor((cur.getTime() - start.getTime()) / 86400000) + 1;
  return diff;
}

// After Day 157 (Oct 11, 2026), use revision schedule
const revisionTopics = [
  // Oct 12 – Nov 29, 2026: Six revision cycles
  { from: '2026-10-12', to: '2026-10-18', topic: 'REVISION CYCLE 1\nLinear Algebra – PYQ Problems\n(Krishna Series + past papers)' },
  { from: '2026-10-19', to: '2026-10-25', topic: 'REVISION CYCLE 2\nCalculus & Real Analysis\nPYQ problems + gap topics' },
  { from: '2026-10-26', to: '2026-11-01', topic: 'REVISION CYCLE 3\nODE & PDE\nPYQ problems + weak areas' },
  { from: '2026-11-02', to: '2026-11-08', topic: 'REVISION CYCLE 4\nComplex Analysis + Vector Analysis\nPYQ problems; contour integrals' },
  { from: '2026-11-09', to: '2026-11-15', topic: 'REVISION CYCLE 5\nAbstract Algebra + LPP\nPYQ problems; proofs' },
  { from: '2026-11-16', to: '2026-11-22', topic: 'REVISION CYCLE 6\nMechanics + Fluid Dynamics\n+ Dynamics + Statics PYQs' },
  { from: '2026-11-23', to: '2026-11-29', topic: 'REVISION CYCLE 7\nNumerical Analysis + Analytic Geometry\nPYQ problems' },
  // Nov 30 – Dec 31, 2026: PYQ Answer Writing
  { from: '2026-11-30', to: '2026-12-06', topic: 'PYQ ANSWER WRITING\nLinear Algebra + Calculus\n(Mains standard; 1-2 answers/day)' },
  { from: '2026-12-07', to: '2026-12-13', topic: 'PYQ ANSWER WRITING\nODE + PDE\n(Mains standard; timed practice)' },
  { from: '2026-12-14', to: '2026-12-20', topic: 'PYQ ANSWER WRITING\nComplex + Vector + NA\n(Mains standard; timed practice)' },
  { from: '2026-12-21', to: '2026-12-27', topic: 'PYQ ANSWER WRITING\nAbstract Algebra + LPP\n(Mains standard; timed practice)' },
  { from: '2026-12-28', to: '2026-12-31', topic: 'PYQ ANSWER WRITING\nMechanics + Statics + Dynamics\n(Mains standard; timed practice)' },
  // Jan–Apr 2027: Prelims phase – math revision in night slot
  { from: '2027-01-01', to: '2027-04-24', topic: 'MATH REVISION (2 hrs)\nSubject-wise rotation (daily)\nMains answer writing practice' },
  // Prelims revision break
  { from: '2027-04-25', to: '2027-05-31', topic: 'MATH MAINTENANCE (1.5 hrs)\nLight revision; formula revision\n+ important theorems' },
  // Post-prelims intensive
  { from: '2027-06-01', to: '2027-08-31', topic: 'MATH INTENSIVE (3-4 hrs)\nFull subject rotation revision\nAnswer writing + mock scripts' },
];

function getMathForDate(y, m, d) {
  const ds = dateStr(y, m, d);
  const day = mathDay(y, m, d);
  if (day >= 1 && day <= 157 && mathByDay[day]) return mathByDay[day];
  // Check revision schedule
  for (const r of revisionTopics) {
    if (ds >= r.from && ds <= r.to) return r.topic;
  }
  return 'Mathematics: Revision & Practice\nSubject rotation (see weekly plan)';
}

// Evening sessions – structured rotation
function getEvening(y, m, d) {
  const date = new Date(y, m-1, d);
  const dow = date.getDay(); // 0=Sun...6=Sat
  const week = Math.floor(mathDay(y,m,d) / 7);
  const ds = dateStr(y, m, d);
  
  // Mathocrat test series: roughly every 2 weeks Jun-Aug 2026 (15 tests)
  const mathTests = [
    '2026-06-06', '2026-06-20', '2026-07-04', '2026-07-18', '2026-08-01',
    '2026-08-15', '2026-08-21'
  ];
  if (mathTests.includes(ds)) return `★ MATHOCRAT SECTIONAL TEST\nMathematics (self-attempted)\n+ review answers`;

  if (dow === 0) return 'Weekly Review & Planning\nConsolidate week\'s notes\n+ plan next week';
  if (dow === 6) return 'Current Affairs (The Hindu)\n+ GS MCQ practice\n+ next week preparation';
  
  const evRotation = [
    'Current Affairs (The Hindu/IE)\nReading + clipping notes\n+ GS topic linkage',
    'GS Notes Making\nConsolidate day\'s GS topic\n+ mind maps / flowcharts',
    'Previous Year Questions (GS)\n10-15 PYQs from today\'s topic\n+ answer analysis',
    'Current Affairs (PIB/Yojana)\nGovernment schemes; policies\n+ note linking',
    'GS Mock MCQ Practice\n20-25 MCQs from week\'s topics\n+ weak areas identification',
  ];
  return evRotation[(week + dow) % evRotation.length];
}

function getNight(y, m, d, monthNum) {
  const dow = new Date(y, m-1, d).getDay();
  const lang = langNote(monthNum);
  const day = mathDay(y, m, d);
  
  if (monthNum <= 2) {
    // 8 hours total: night = 1 hour
    if (dow === 0) return 'Weekly self-assessment\nNote gaps & update plan\n(30 min + 30 min language)';
    return lang;
  }
  
  // 10 hours total: night = 3 hours
  const revRotation10 = [
    `Math Quick Revision (1 hr)\nToday's math topic flashcards\n+ ${lang}`,
    `GS Revision (1 hr)\nToday's GS topic key points\n+ ${lang}`,
    `Math PYQ solving (1.5 hrs)\n2 mains-standard answers\n+ language (1 hr)`,
    `GS Answer Writing (1.5 hrs)\n1 GS mains answer (250 words)\n+ language (1 hr)`,
    `Current Affairs revision (1 hr)\nWeek's CA consolidation\n+ language (1 hr)`,
  ];
  const dow2 = new Date(y, m-1, d).getDay();
  return revRotation10[dow2 % revRotation10.length];
}


export { mathByDay, gsByDate, revisionTopics, langNote, mathDay, getMathForDate, getEvening, getNight, dateStr };
